apiVersion: v1
kind: Pod
metadata:
  name: random-cpu
spec:
  containers:
  - name: random-cpu
    image: busybox
    command:
      - sh
      - -c
      - |
        while true; do
          # Generate a random CPU load between 0 and 100% of 1 core
          RAND=$(( RANDOM % 100 ))
          echo "CPU load: $RAND"
          # Busy loop for a short random time to simulate usage
          END=$(( SECONDS + RAND % 3 ))
          while [ $SECONDS -lt $END ]; do :; done
          # Sleep briefly between bursts
          sleep 0.5
        done
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "1000m"
