apiVersion: v1
kind: Pod
metadata:
  name: random-cpu
spec:
  containers:
  - name: cpu-burner
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "Burning CPU..."
        while true; do
          sha256sum /dev/zero > /dev/null 2>&1 &
          sha256sum /dev/zero > /dev/null 2>&1 &
          sha256sum /dev/zero > /dev/null 2>&1 &
          sha256sum /dev/zero > /dev/null 2>&1
        done
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "1"
